server:
  port: 8080
  allowOrigins:
    # - "*"  //for development
    - "https://example.com"
    - "https://api.example.com"

  bodyLimit: 1048576
  timeout: 30s # Seconds
  jwt_secret_key: "my-secure-secret-key"
 

database:
  host: localhost   
  port: 5432
  user: postgres
  password: 123456
  dbname: postgres
  sslmode: disable
  schema: public

